name: weekly-rebuild
on:
  push:
    branches: ["master"]
  schedule:
    - cron: '0 0 * * 0'
jobs:
  # Build job
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: git.saintnet.tech
          username: ${{ gitea.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build and push
        env:
          IMAGE_NAME: haldap
          REGISTRY: git.saintnet.tech
          REPO_OWNER: stryan
        run: "TODAY=$(date +'%Y-%m-%d')\ndocker build -t ${REGISTRY}/${REPO_OWNER}/${IMAGE_NAME}:latest -f Containerfile .\ndocker push ${REGISTRY}/${REPO_OWNER}/${IMAGE_NAME}:latest          \n"
